services:

  postgres:
    image: postgres:17

    container_name: ai_knowledge_platform_server

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis/redis-stack:latest
    container_name: ai_redis
    restart: unless-stopped

    ports:
      - "8007:6379"
      - "8009:8001"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  rabbitmq:
    image: rabbitmq:4-management

    container_name: ai_rabbitmq

    restart: unless-stopped

    env_file:
      - .env

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASSWORD}

    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15673:15672"

    healthcheck:
      test:
        [
          "CMD",
          "rabbitmq-diagnostics",
          "-q",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  ai-base:
    image: ai-base:latest

    build:
      context: .
      dockerfile: Dockerfile.base


  gateway_service:
    image: gateway_service:latest

    build:
      context: .
      dockerfile: services/gateway/Dockerfile

    container_name: gateway_service

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  auth_service:
    image: auth_service:latest

    build:
      context: .
      dockerfile: services/auth/Dockerfile

    container_name: auth_service

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8001:8001"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  file_service:
    image: file_service:latest

    build:
      context: .
      dockerfile: services/file/Dockerfile

    container_name: file_service

    restart: unless-stopped

    env_file:
      - .env
    
    ports:
      - "8002:8002"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      worker_service:
        condition: service_started


  embedding_service:
    image: embedding_service:latest

    build:
      context: .
      dockerfile: services/embedding/Dockerfile

    container_name: embedding_service

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8003:8003"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  search_service:
    image: search_service:latest

    build:
      context: .
      dockerfile: services/search/Dockerfile

    container_name: search_service

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8004:8004"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  ai_service:
    image: ai_service:latest

    build:
      context: .
      dockerfile: services/ai/Dockerfile

    container_name: ai_service

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8005:8005"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  worker_service:
    image: worker_service:latest

    build:
      context: .
      dockerfile: services/worker/Dockerfile

    container_name: worker_service

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8006:8006"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  celery_worker:
    image: worker_service:latest

    command:
      - celery
      - -A
      - services.worker.app.celery_app.celery_app
      - worker
      - --loglevel=info
      - --without-mingle
      - --without-gossip

    container_name: celery_worker

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      worker_service:
        condition: service_started


  celery_beat:
    image: worker_service:latest

    command:
      - celery
      - -A
      - services.worker.app.celery_app.celery_app
      - beat
      - --loglevel=info

    container_name: celery_beat

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      worker_service:
        condition: service_started


  prometheus:
    image: prom/prometheus:v3.5.0

    container_name: ai_prometheus

    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

    depends_on:
      gateway_service:
        condition: service_started
      celery_worker:
        condition: service_started


volumes:
  postgres_data: