"""previous version

Revision ID: 5e04fc60e556
Revises: 78cd4ebccb75
Create Date: 2026-07-30 07:13:51.584314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e04fc60e556'
down_revision: Union[str, Sequence[str], None] = '78cd4ebccb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_auth', 'role',
               existing_type=postgresql.ENUM('user', 'admin', name='role'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_auth_doc_id'), table_name='user_auth')
    op.drop_column('user_auth', 'doc_type')
    op.drop_column('user_auth', 'doc_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('doc_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_auth', sa.Column('doc_type', postgresql.ENUM('pdf', 'txt', name='doctype'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_user_auth_doc_id'), 'user_auth', ['doc_id'], unique=True)
    op.alter_column('user_auth', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('user', 'admin', name='role'),
               existing_nullable=False)
    # ### end Alembic commands ###
