"""from maulik sir

Revision ID: 78cd4ebccb75
Revises: 0002
Create Date: 2026-07-30 06:27:19.821544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78cd4ebccb75'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('role', sa.Enum('user', 'admin', name='role'), nullable=False))
    op.add_column('user_auth', sa.Column('doc_type', sa.Enum('pdf', 'txt', name='doctype'), nullable=False))
    op.drop_column('user_auth', 'doc_type_enum')
    op.drop_column('user_auth', 'role_enum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('role_enum', postgresql.ENUM('user', 'admin', name='role'), autoincrement=False, nullable=False))
    op.add_column('user_auth', sa.Column('doc_type_enum', postgresql.ENUM('pdf', 'txt', name='doctype'), autoincrement=False, nullable=False))
    op.drop_column('user_auth', 'doc_type')
    op.drop_column('user_auth', 'role')
    # ### end Alembic commands ###
