"""from maulik sir

Revision ID: f7734eb3a6cb
Revises: 5e04fc60e556
Create Date: 2026-07-30 07:17:20.626050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7734eb3a6cb'
down_revision: Union[str, Sequence[str], None] = '5e04fc60e556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('doc_id', sa.String(), nullable=True))
    op.add_column('user_auth', sa.Column('doc_type', sa.Enum('pdf', 'txt', name='doctype'), nullable=True))
    op.alter_column('user_auth', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('user', 'admin', name='role'),
               existing_nullable=False)
    op.create_index(op.f('ix_user_auth_doc_id'), 'user_auth', ['doc_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_auth_doc_id'), table_name='user_auth')
    op.alter_column('user_auth', 'role',
               existing_type=sa.Enum('user', 'admin', name='role'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('user_auth', 'doc_type')
    op.drop_column('user_auth', 'doc_id')
    # ### end Alembic commands ###
