class AuthRepository:
    async def search_username(username, db):
        ...

    async def search_email(email, db):
        ...

    async def register_user(user_credentials, hashed_password,db):
        ...

    async def get_password(username, db):
        ...