FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml .

RUN pip install uv
RUN uv pip install --system .

COPY . .

EXPOSE {{ service_port }}

CMD ["uvicorn", "services.{{ service_name }}.app.main:app", "--host", "0.0.0.0", "--port", "{{ service_port }}"]