FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install uv

RUN uv pip install --system .

EXPOSE {{ service_port }}

CMD ["uvicorn", "{{ service_name }}.app.main:app", "--host", "0.0.0.0", "--port", "{{ service_port }}"]